### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by NicoAiko** [rundef/node-testrail-api#5]
I get this error when I try to test `testrail.deleteSection`

Here's the output message in my terminal.
```javascript
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (...path/node_modules/testrail-api/index.js:88:29)
    at Request.self.callback (...path/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (...path/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (...path/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

And here's my test code:

```javascript
const sectionObject = {
  name: 'Test Section',
};

testrailInstance.addSection(projectId, sectionObject)
  .then((result) => {
    testrailInstance.deleteSection(result.id)
      .then(console.log)
      .catch(console.log);
  })
  .catch(console.error);
```

What's going on here? It can't `JSON.parse` the result?

**Comment by NicoAiko** [comment]
The section was deleted, so the request itself was successful. But it doesn't give a proper response which is pretty unfortunate in terms of testing...

**Comment by NicoAiko** [comment]
@rundef Any response...?
